package com.dika.res

object SmallIconRes: IconResource("smallIcon/") {
    val appsIcon get() = load("smallFrameIco.png")
    val calculatorIcon get() = load("calculator.png")
    val cancelIcon get() = load("cancel.png")
    val searchIcon get() = load("cari.png")
    val clearIcon get() = load("clear.png")
    val dotIcon get() = load("dot.png")
    val updateIcon get() = load("edit.png")
    val exitIcon get() = load("exit.png")
    val seeIcon get() = load("eye.png")
    val loginIcon get() = load("login.png")
    val logoutIcon get() = load("logout.png")
    val officeIcon get() = load("office.png")
    val addIcon get() = load("add.png")
    val printIcon get() = load("print.png")
    val refreshIcon get() = load("refresh.png")
    val requireIcon get() = load("require.png")
    val saveIcon get() = load("save.png")
    val infoIcon get() = load("info.png")
    val settingIcon get() = load("setting.png")
    val confirmIcon get() = load("flagGreen.png")
    val unconfirmIcon get() = load("flagRed.png")
    val nextIcon get() = load("next.png")
    val previousIcon get() = load("prev.png")
    val firstPageIcon get() = load("first_page.png")
    val lastPageIcon get() = load("last_page.png")
    val keyBlueIcon get() = load("key_blue.png")
    val userIcon get() = load("user.png")
    val user20Icon get() = load("user20.png")
}